DROP TABLE IF EXISTS MSG_MENSAJE CASCADE;

CREATE TABLE IF NOT EXISTS MSG_MENSAJE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TOPICO VARCHAR(255) NOT NULL,
    FECHA_REGISTRO TIMESTAMP NOT NULL,
    CABECERAS TEXT,
    MENSAJE TEXT NOT NULL,
    PRIMARY KEY (ID)
);